// Mock in-memory database for development (when MongoDB is not available)

const mockProducts = [
  // Smartphones
  {
    _id: "1",
    name: "iPhone 15 Pro Max",
    description:
      "Latest Apple flagship with A17 Pro chip, 6.7-inch display, 48MP camera, titanium design",
    price: 1199.99,
    image: "https://via.placeholder.com/400x300?text=iPhone+15+Pro+Max",
    category: "Smartphones",
    tags: ["iphone", "smartphone", "apple", "premium", "camera"],
    countInStock: 12,
    rating: 4.9,
    numReviews: 234,
  },
  {
    _id: "2",
    name: "Samsung Galaxy S24 Ultra",
    description:
      "Flagship Android with AI features, 108MP camera, 6.9-inch display, 120Hz refresh rate",
    price: 1299.99,
    image: "https://via.placeholder.com/400x300?text=Galaxy+S24+Ultra",
    category: "Smartphones",
    tags: ["samsung", "smartphone", "android", "ai", "flagship"],
    countInStock: 15,
    rating: 4.8,
    numReviews: 189,
  },
  {
    _id: "3",
    name: "OnePlus 12 Pro",
    description:
      "5G smartphone with 240W charging, Snapdragon 8 Gen 3, 120Hz AMOLED, 50MP camera",
    price: 749.99,
    image: "https://via.placeholder.com/400x300?text=OnePlus+12+Pro",
    category: "Smartphones",
    tags: ["oneplus", "smartphone", "5g", "fast", "performance"],
    countInStock: 20,
    rating: 4.7,
    numReviews: 156,
  },
  {
    _id: "4",
    name: "Google Pixel 8 Pro",
    description:
      "Google's premium phone with Tensor 3, advanced AI, 50MP main camera, 6.7-inch display",
    price: 999.99,
    image: "https://via.placeholder.com/400x300?text=Pixel+8+Pro",
    category: "Smartphones",
    tags: ["google", "pixel", "ai", "camera", "android"],
    countInStock: 18,
    rating: 4.8,
    numReviews: 167,
  },
  {
    _id: "5",
    name: "MacBook Pro 16-inch M3 Max",
    description:
      "Professional laptop with Apple M3 Max chip, 16GB unified memory, 512GB SSD, excellent for developers",
    price: 2499.99,
    image: "https://via.placeholder.com/400x300?text=MacBook+Pro",
    category: "Laptops",
    tags: ["macbook", "laptop", "pro", "m3", "developer"],
    countInStock: 8,
    rating: 4.9,
    numReviews: 198,
  },
  {
    _id: "6",
    name: "Dell XPS 15",
    description:
      "High-performance ultrabook with Intel Core i9, RTX 4070, 16-inch OLED display, aluminum design",
    price: 1799.99,
    image: "https://via.placeholder.com/400x300?text=Dell+XPS+15",
    category: "Laptops",
    tags: ["dell", "laptop", "xps", "gaming", "professional"],
    countInStock: 10,
    rating: 4.8,
    numReviews: 145,
  },
  {
    _id: "7",
    name: "ASUS ROG Gaming Laptop",
    description:
      "Gaming powerhouse with RTX 4090, Intel i9-13900HX, 16-inch 240Hz display, advanced cooling",
    price: 2199.99,
    image: "https://via.placeholder.com/400x300?text=ASUS+ROG",
    category: "Laptops",
    tags: ["asus", "rog", "gaming", "laptop", "powerful"],
    countInStock: 6,
    rating: 4.7,
    numReviews: 132,
  },
  {
    _id: "8",
    name: "Sony WH-1000XM5",
    description:
      "Premium wireless headphones with best-in-class noise cancellation, 30-hour battery, Hi-Res audio",
    price: 399.99,
    image: "https://via.placeholder.com/400x300?text=Sony+WH-1000XM5",
    category: "Audio",
    tags: ["headphones", "wireless", "noise-cancelling", "sony", "premium"],
    countInStock: 20,
    rating: 4.8,
    numReviews: 287,
  },
  {
    _id: "9",
    name: "Apple AirPods Pro Max",
    description:
      "Apple's flagship over-ear headphones with spatial audio, active noise cancellation, premium build",
    price: 549.99,
    image: "https://via.placeholder.com/400x300?text=AirPods+Pro+Max",
    category: "Audio",
    tags: ["airpods", "headphones", "apple", "premium", "audio"],
    countInStock: 15,
    rating: 4.7,
    numReviews: 156,
  },
  {
    _id: "10",
    name: "JBL PartyBox 720",
    description:
      "Portable Bluetooth speaker system with dual woofers, 2000W power, built-in DJ effects, lights",
    price: 799.99,
    image: "https://via.placeholder.com/400x300?text=JBL+PartyBox",
    category: "Audio",
    tags: ["speaker", "bluetooth", "party", "jbl", "powerful"],
    countInStock: 12,
    rating: 4.6,
    numReviews: 98,
  },
  {
    _id: "11",
    name: "Nike Air Max 270",
    description:
      "Classic running shoe with Air cushioning, breathable mesh, available in multiple colors",
    price: 129.99,
    image: "https://via.placeholder.com/400x300?text=Nike+Air+Max+270",
    category: "Fashion",
    tags: ["shoes", "nike", "running", "casual", "comfortable"],
    countInStock: 45,
    rating: 4.7,
    numReviews: 312,
  },
  {
    _id: "12",
    name: "Adidas Ultraboost 22",
    description:
      "High-performance running shoe with Boost technology, comfortable for all-day wear",
    price: 179.99,
    image: "https://via.placeholder.com/400x300?text=Adidas+Ultraboost",
    category: "Fashion",
    tags: ["shoes", "adidas", "running", "sport", "performance"],
    countInStock: 38,
    rating: 4.6,
    numReviews: 267,
  },
  {
    _id: "13",
    name: "Levi's 501 Jeans",
    description:
      "Classic blue denim jeans, 100% cotton, perfect fit for everyday wear, timeless design",
    price: 79.99,
    image: "https://via.placeholder.com/400x300?text=Levis+501",
    category: "Fashion",
    tags: ["jeans", "clothing", "casual", "levis", "durable"],
    countInStock: 60,
    rating: 4.5,
    numReviews: 289,
  },
  {
    _id: "14",
    name: "Apple Watch Series 9",
    description:
      "Smartwatch with always-on display, health monitoring, fitness tracking, water-resistant",
    price: 399.99,
    image: "https://via.placeholder.com/400x300?text=Apple+Watch+9",
    category: "Electronics",
    tags: ["watch", "smartwatch", "apple", "fitness", "health"],
    countInStock: 22,
    rating: 4.7,
    numReviews: 345,
  },
  {
    _id: "15",
    name: "iPad Pro 12.9-inch",
    description:
      "Premium tablet with M2 chip, 12.9-inch Liquid Retina display, Apple Pencil support",
    price: 1099.99,
    image: "https://via.placeholder.com/400x300?text=iPad+Pro",
    category: "Electronics",
    tags: ["ipad", "tablet", "apple", "pro", "premium"],
    countInStock: 16,
    rating: 4.8,
    numReviews: 287,
  },
  {
    _id: "16",
    name: "GoPro Hero 12",
    description:
      "Action camera with 4K video, waterproof design, hypersmooth stabilization, rugged build",
    price: 449.99,
    image: "https://via.placeholder.com/400x300?text=GoPro+Hero+12",
    category: "Electronics",
    tags: ["camera", "gopro", "action", "video", "adventure"],
    countInStock: 18,
    rating: 4.6,
    numReviews: 167,
  },
  {
    _id: "17",
    name: "PlayStation 5 Console",
    description:
      "Latest gaming console with 825GB SSD, 4K support, exclusive games, wireless controller",
    price: 499.99,
    image: "https://via.placeholder.com/400x300?text=PS5",
    category: "Gaming",
    tags: ["gaming", "console", "playstation", "ps5", "entertainment"],
    countInStock: 5,
    rating: 4.8,
    numReviews: 456,
  },
  {
    _id: "18",
    name: "Xbox Series X",
    description:
      "Microsoft's next-gen console with 1TB storage, 4K/120fps gaming, Game Pass included",
    price: 499.99,
    image: "https://via.placeholder.com/400x300?text=Xbox+Series+X",
    category: "Gaming",
    tags: ["gaming", "console", "xbox", "microsoft", "entertainment"],
    countInStock: 6,
    rating: 4.7,
    numReviews: 389,
  },
  {
    _id: "19",
    name: "Nintendo Switch Pro",
    description:
      "Handheld gaming console with hybrid design, detachable controllers, 128GB storage",
    price: 349.99,
    image: "https://via.placeholder.com/400x300?text=Nintendo+Switch",
    category: "Gaming",
    tags: ["gaming", "console", "nintendo", "switch", "portable"],
    countInStock: 22,
    rating: 4.6,
    numReviews: 267,
  },
  {
    _id: "20",
    name: "KitchenAid Stand Mixer",
    description:
      "Professional 5-quart stand mixer, 10 speeds, stainless steel bowl, perfect for baking",
    price: 329.99,
    image: "https://via.placeholder.com/400x300?text=KitchenAid+Mixer",
    category: "Home & Kitchen",
    tags: ["kitchen", "mixer", "appliance", "baking", "professional"],
    countInStock: 14,
    rating: 4.8,
    numReviews: 234,
  },
];

export default mockProducts;
